# Generated by Django 5.1.3 on 2024-11-24 15:11

import django.core.validators
import django.db.models.deletion
import setup.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Full registered name of the company', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Company Name')),
                ('trading_name', models.CharField(blank=True, help_text='Business name used for trading (if different from registered name)', max_length=255, verbose_name='Trading Name')),
                ('registration_number', models.CharField(help_text='Official company registration number', max_length=50, unique=True, verbose_name='Registration Number')),
                ('tax_number', models.CharField(blank=True, help_text='Tax identification number', max_length=50, null=True, unique=True, verbose_name='Tax ID Number')),
                ('phone', models.CharField(help_text='Primary contact number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('email', models.EmailField(help_text='Primary contact email', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address')),
                ('website', models.URLField(blank=True, help_text='Company website URL', verbose_name='Website')),
                ('address_line1', models.CharField(help_text='Street address', max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, help_text='Apartment, suite, unit, etc.', max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(help_text='City name', max_length=100, verbose_name='City')),
                ('state', models.CharField(help_text='State or province name', max_length=100, verbose_name='State/Province')),
                ('country', models.CharField(help_text='Country name', max_length=100, verbose_name='Country')),
                ('postal_code', models.CharField(help_text='Postal or ZIP code', max_length=20, verbose_name='Postal Code')),
                ('logo', models.ImageField(blank=True, help_text='Company logo (max 5MB)', null=True, upload_to='company_logos/', validators=[setup.models.validate_file_size], verbose_name='Company Logo')),
                ('description', models.TextField(blank=True, help_text='Brief description of the company', verbose_name='Description')),
                ('establishment_date', models.DateField(blank=True, help_text='Date when company was established', null=True, verbose_name='Establishment Date')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the company is currently active', verbose_name='Active Status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
                'permissions': [('view_company_details', 'Can view company details'), ('manage_company', 'Can manage company information')],
                'indexes': [models.Index(fields=['name'], name='setup_compa_name_f91ef6_idx'), models.Index(fields=['registration_number'], name='setup_compa_registr_38eabd_idx')],
            },
        ),
    ]
