# Generated by Django 5.1.3 on 2024-11-24 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_companylocation_locationauditlog_locationtype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('responsible_person', models.CharField(blank=True, max_length=255, null=True)),
                ('is_main_department', models.BooleanField(default=False)),
                ('is_ipd', models.BooleanField(default=False, verbose_name='Is Internal Department (IPD)')),
                ('ipd_value_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_medical_package', models.BooleanField(default=False, verbose_name='Is Medical Package')),
                ('issue_inventory', models.BooleanField(default=False, verbose_name='Issue Inventory to Department')),
                ('is_laboratory', models.BooleanField(default=False, verbose_name='Is Laboratory Department')),
                ('laboratory_type', models.CharField(blank=True, choices=[('in-house', 'In-House'), ('outside', 'Outside'), ('partner_company', 'Partner Company'), ('sister_company', 'Sister Company')], max_length=20, null=True)),
                ('is_operation_theater', models.BooleanField(default=False, verbose_name='Is Operation Theater')),
                ('operation_theater_date_mandatory', models.BooleanField(default=False, verbose_name='Is Date Mandatory for Operation Theater')),
                ('allow_discounts', models.BooleanField(default=False, verbose_name='Allow Discounts')),
                ('max_discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('income_account', models.CharField(blank=True, max_length=255, null=True)),
                ('expense_account', models.CharField(blank=True, max_length=255, null=True)),
                ('modify_invoice_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Invoice Number Modification')),
                ('issue_sequence_number', models.BooleanField(default=False, verbose_name='Issue Sequence Number')),
                ('issue_sequence_auto', models.BooleanField(default=True, verbose_name='Auto Sequence')),
                ('department_wise_sequence', models.BooleanField(default=False, verbose_name='Department Wise Sequence')),
                ('department_sequence_per_day', models.BooleanField(default=False, verbose_name='Department Sequence Per Day')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='setup.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_created_by', to=settings.AUTH_USER_MODEL)),
                ('locations', models.ManyToManyField(related_name='departments', to='setup.companylocation')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
