# Generated by Django 5.1.3 on 2024-11-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='Code',
            field=models.CharField(default='DEF', max_length=15),
        ),
    ]
