# Generated by Django 5.1.3 on 2024-11-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_department_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='outside_value_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Outside Commission Rate'),
        ),
        migrations.AlterField(
            model_name='department',
            name='ipd_value_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Internal Department (IPD) Rate for Services'),
        ),
        migrations.AlterField(
            model_name='department',
            name='max_discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
