# Generated by Django 5.1.3 on 2024-11-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_department_outside_value_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='outside_value_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Outside Commission Rate (%)'),
        ),
    ]
