# Generated by Django 5.1.3 on 2024-11-24 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_alter_department_outside_value_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClarificationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Clarification Code')),
                ('name', models.CharField(max_length=255, verbose_name='Clarification Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_income', models.BooleanField(default=False, verbose_name='Is Income Transaction')),
                ('is_expense', models.BooleanField(default=False, verbose_name='Is Expense Transaction')),
                ('is_adjustment', models.BooleanField(default=False, verbose_name='Is Adjustment Transaction')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='Requires Approval')),
                ('auto_post', models.BooleanField(default=False, verbose_name='Auto Post Transaction')),
                ('max_transaction_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Max Transaction Value')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clarification_created_by', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(related_name='ClarificationDetailDepartments', to='setup.department', verbose_name='Associated Departments')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clarification_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clarification Detail',
                'verbose_name_plural': 'Clarification Details',
            },
        ),
        migrations.CreateModel(
            name='ClassDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=20, unique=True, verbose_name='Class Code')),
                ('name', models.CharField(max_length=255, verbose_name='Class Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('management_account_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Management Account ID')),
                ('accounting_enabled', models.BooleanField(default=False, verbose_name='Enable Accounting')),
                ('income_account', models.CharField(blank=True, max_length=255, null=True, verbose_name='Income Account Reference')),
                ('expense_account', models.CharField(blank=True, max_length=255, null=True, verbose_name='Expense Account Reference')),
                ('max_posting_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Max Posting Limit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_created_by', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(related_name='classesDepartments', to='setup.department', verbose_name='Associated Departments')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class Detail',
                'verbose_name_plural': 'Class Details',
            },
        ),
    ]
