# Generated by Django 5.1.3 on 2024-11-24 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_taxcode_laboratorydepartment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaxCode',
        ),
    ]
