# Generated by Django 5.1.3 on 2024-11-24 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0010_delete_taxcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.IntegerField(default=0)),
                ('include_exclude', models.CharField(choices=[('Include', 'Include'), ('Exclude', 'Exclude')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TaxCodecompany', to='setup.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TaxCode_created_by', to=settings.AUTH_USER_MODEL)),
                ('locations', models.ManyToManyField(related_name='TaxCodelocations', to='setup.companylocation')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TaxCode_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tax Code',
                'verbose_name_plural': 'Tax Codes',
            },
        ),
    ]
