# Generated by Django 5.1.3 on 2024-11-24 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0013_taxcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(max_length=50)),
                ('service_Name', models.CharField(max_length=250)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_barcode', models.CharField(max_length=100)),
                ('rate_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('print_lab_note', models.BooleanField(default=False)),
                ('highlight_in_diagnosis_sheet', models.BooleanField(default=False)),
                ('allowed_discount', models.BooleanField(default=False)),
                ('max_allowed_discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('include_tax', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Servicecompany', to='setup.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Service_created_by', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Servicedepartments', to='setup.department', verbose_name='Associated Departments')),
                ('laboratorydepartments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LaboratoryDepartment', to='setup.laboratorydepartment', verbose_name='Associated Laboratory Departments')),
                ('locations', models.ManyToManyField(related_name='Servicelocations', to='setup.companylocation')),
                ('tax_code', models.ManyToManyField(related_name='ServiceTaxies', to='setup.taxcode')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Service_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Registration',
                'verbose_name_plural': 'Service Registrations',
            },
        ),
    ]
