# Generated by Django 5.1.3 on 2024-11-24 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0015_alter_service_allowed_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxcode',
            name='company',
        ),
        migrations.RemoveField(
            model_name='taxcode',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='taxcode',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='taxcode',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='TaxCode',
        ),
    ]
