# Generated by Django 5.1.3 on 2024-11-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0017_taxcode_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='tax_code',
            field=models.ManyToManyField(null=True, related_name='service_taxes', to='setup.taxcode', verbose_name='Tax Code(s)'),
        ),
    ]
