# Generated by Django 5.1.3 on 2024-11-24 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0019_alter_service_laboratory_departments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='laboratory_departments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_departments', to='setup.laboratorydepartment', verbose_name='Associated Laboratory Departments'),
        ),
    ]
