# Generated by Django 5.1.3 on 2024-11-24 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0021_alter_service_remarks_suppliertype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplierType',
        ),
    ]
