# Generated by Django 5.1.3 on 2024-11-24 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0023_suppliertype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupplierType',
            new_name='ConsultationSupplierType',
        ),
        migrations.CreateModel(
            name='SupplierRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_type_sys_code', models.CharField(choices=[('1', 'Consultations (Doctor)'), ('2', 'Service Supplier'), ('3', 'Item Supplier'), ('4', 'MLT'), ('5', 'Other')], default='1', max_length=1, verbose_name='Supplier Type')),
                ('sup_user_code', models.CharField(max_length=15, unique=True, verbose_name='Supplier User Code')),
                ('sup_title', models.CharField(default='', max_length=15, verbose_name='Supplier Title')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Non', 'Non')], default='Non', max_length=15, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('sup_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Supplier Name')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Person')),
                ('license_number', models.CharField(default='', max_length=50, verbose_name='License Number')),
                ('add1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 1')),
                ('add2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 2')),
                ('add3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 3')),
                ('tel1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telephone 1')),
                ('tel2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telephone 2')),
                ('fax', models.CharField(blank=True, max_length=15, null=True, verbose_name='Fax')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email Address')),
                ('web', models.URLField(blank=True, max_length=100, null=True, verbose_name='Website URL')),
                ('vat_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='VAT Number')),
                ('edb_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='EDB Number')),
                ('invoice_code', models.CharField(default='', max_length=2, verbose_name='Invoice Code')),
                ('department_wise_invoice', models.BooleanField(default=False, verbose_name='Department Wise Invoice')),
                ('remarks', models.TextField(blank=True, max_length=250, verbose_name='Remarks')),
                ('company', models.ManyToManyField(related_name='supplier_registration_company', to='setup.company', verbose_name='Company')),
                ('con_user_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_supplier_type', to='setup.consultationsuppliertype', verbose_name='Consultation Type')),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_departments', to='setup.department', verbose_name='Default Department')),
                ('locations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_registration_locations', to='setup.companylocation', verbose_name='Default Location')),
            ],
            options={
                'verbose_name': 'Supplier Registration',
                'verbose_name_plural': 'Supplier Registrations',
                'db_table': 'supplier_registration',
            },
        ),
    ]
