# Generated by Django 5.1.3 on 2024-11-24 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0024_rename_suppliertype_consultationsuppliertype_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplierRegistration',
        ),
    ]
