# Generated by Django 5.1.3 on 2024-11-24 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0025_delete_supplierregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_type_sys_code', models.CharField(choices=[('1', 'Consultations (Doctor)'), ('2', 'Service Supplier'), ('3', 'Item Supplier'), ('4', 'MLT'), ('5', 'Other')], default='1', max_length=1, verbose_name='Supplier Type')),
                ('sup_user_code', models.CharField(max_length=15, unique=True, verbose_name='Supplier User Code')),
                ('sup_titel', models.CharField(default='', max_length=15, verbose_name='Supplier Title')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Non', 'Non')], default='Non', max_length=15, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('sup_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Supplier Name')),
                ('cheque_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cheque Title')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Person')),
                ('license_number', models.CharField(default='', max_length=50, verbose_name='License Number')),
                ('add1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 1')),
                ('add2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 2')),
                ('add3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 3')),
                ('tel1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telephone 1')),
                ('tel2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telephone 2')),
                ('tele3', models.CharField(default='', max_length=15, verbose_name='Telephone 3')),
                ('fax', models.CharField(blank=True, max_length=15, null=True, verbose_name='Fax Number')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email Address')),
                ('web', models.URLField(default='', max_length=100, verbose_name='Website URL')),
                ('full_acc_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Full Account Code')),
                ('sub_acc_sys_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sub Account System Code')),
                ('edb_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='EDB Number')),
                ('vat_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='VAT Number')),
                ('tqb_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='TQB Number')),
                ('boi_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='BOI Number')),
                ('invoice_code', models.CharField(default='', max_length=2, verbose_name='Invoice Code')),
                ('inv_no_sup_wise', models.BooleanField(default=False, verbose_name='Department Wise Invoice Number')),
                ('dep_wise_sequence_no_yes', models.BooleanField(default=False, verbose_name='Department Wise Invoice Number Per Day')),
                ('e_channeling_ref_no', models.CharField(default='', max_length=15, verbose_name='E-Channeling Reference Number')),
                ('app_wtax', models.BooleanField(default=False, verbose_name='App Withholding Tax')),
                ('app_wtax_pre', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='App Withholding Tax %')),
                ('app_wtax_no', models.CharField(default='', max_length=15, verbose_name='App Withholding Tax Number')),
                ('sms_name', models.CharField(default='', max_length=200, verbose_name='Digital SMS Name')),
                ('remarks', models.CharField(default='', max_length=250, verbose_name='Remarks')),
                ('acc_head_code', models.CharField(default='', max_length=25, verbose_name='Account Head Code')),
                ('acc_code', models.CharField(default='', max_length=25, verbose_name='Account Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_registration_company', to='setup.company', verbose_name='Company')),
                ('con_user_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_supplier_type', to='setup.consultationsuppliertype', verbose_name='Consultation Type')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_registration_created_by', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_departments', to='setup.department', verbose_name='Default Department')),
                ('locations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_registration_locations', to='setup.companylocation', verbose_name='Default Location')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_registration_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier Registration',
                'verbose_name_plural': 'Supplier Registrations',
                'db_table': 'supplier_registration',
                'unique_together': {('company', 'sup_user_code')},
            },
        ),
    ]
