# Generated by Django 5.1.3 on 2024-11-24 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0026_supplierregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplierRegistration',
        ),
    ]
