# Generated by Django 5.1.3 on 2024-11-24 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0029_supplierdepartmentdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplierDepartmentDetails',
        ),
    ]
