# Generated by Django 5.1.3 on 2024-11-24 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0030_delete_supplierdepartmentdetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierDepartmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channeling_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Channeling Rate')),
                ('hospital_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hospital Rate')),
                ('rate_cost_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rate (Cost) per Day')),
                ('is_doctor_fees', models.BooleanField(default=False, verbose_name='Is Doctor Fees')),
                ('number_of_appointments', models.IntegerField(default=0, verbose_name='Number of Appointments')),
                ('appointment_duration', models.DurationField(blank=True, null=True, verbose_name='Appointment Duration (HH:MM)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_registration_companyDepartment', to='setup.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_department_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_department_details_departments', to='setup.department', verbose_name='Associated Departments')),
                ('hospital_services_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_department_hospital_services_code', to='setup.service', verbose_name='Hospital Services Code')),
                ('locations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_registration_locationsDepartment', to='setup.companylocation', verbose_name='Location')),
                ('services_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_department_service_details', to='setup.service', verbose_name='Services Code')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_details', to='setup.supplierregistration', verbose_name='Supplier')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_department_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Supplier Department Detail',
                'verbose_name_plural': 'Supplier Department Details',
                'db_table': 'supplier_department_details',
            },
        ),
    ]
