# Generated by Django 5.1.3 on 2024-11-24 23:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0034_supplierdepartmentdetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplierdepartmentdetails',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='supplierdepartmentdetails',
            constraint=models.UniqueConstraint(fields=('company', 'locations', 'supplier', 'departments'), name='unique_supplier_department_details'),
        ),
    ]
