# Generated by Django 5.1.3 on 2024-11-24 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0035_alter_supplierdepartmentdetails_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierdepartmentdetails',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_registration_company_department', to='setup.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='supplierdepartmentdetails',
            name='locations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_registration_locations_department', to='setup.companylocation', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='supplierdepartmentdetails',
            name='number_of_appointments',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Appointments'),
        ),
    ]
