# Generated by Django 5.1.3 on 2024-11-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0036_alter_supplierdepartmentdetails_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='tax_code',
            field=models.ManyToManyField(blank=True, related_name='service_taxes', to='setup.taxcode', verbose_name='Tax Code(s)'),
        ),
    ]
