# Generated by Django 5.1.3 on 2024-11-25 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0037_alter_service_tax_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLocationPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rate')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost Price')),
                ('minimum_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimum Price')),
                ('item_barcode', models.CharField(max_length=100, verbose_name='Item Barcode')),
                ('rate_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rate Per Day')),
                ('remarks', models.TextField(blank=True, default='', max_length=100, null=True, verbose_name='Remarks')),
                ('print_lab_note', models.BooleanField(default=False, verbose_name='Print Laboratory Note')),
                ('allowed_discount', models.BooleanField(default=False, verbose_name='Allowed Discount')),
                ('max_allowed_discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Max Allowed Discount (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_CompanylocationsPrice', to='setup.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serviceLocPrice_created_by', to=settings.AUTH_USER_MODEL)),
                ('locations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_locationsService', to='setup.companylocation')),
                ('service_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_LocationPrice', to='setup.service')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serviceLOcPrice_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Location Price Registrations',
                'verbose_name_plural': 'Service Location Price Registrations',
                'unique_together': {('Company', 'locations', 'service_code')},
            },
        ),
    ]
