# Generated by Django 5.1.3 on 2024-11-25 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0038_servicelocationprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceLocationPrice',
        ),
    ]
