# Generated by Django 5.1.3 on 2024-11-25 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0039_delete_servicelocationprice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLocationPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rate')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost Price')),
                ('minimum_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimum Price')),
                ('item_barcode', models.CharField(max_length=100, verbose_name='Item Barcode')),
                ('rate_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rate Per Day')),
                ('remarks', models.TextField(blank=True, default='', max_length=100, null=True, verbose_name='Remarks')),
                ('print_lab_note', models.BooleanField(default=False, verbose_name='Print Laboratory Note')),
                ('allowed_discount', models.BooleanField(default=False, verbose_name='Allowed Discount')),
                ('max_allowed_discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Max Allowed Discount (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_company_locations_price', to='setup.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_loc_price_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('locations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_location_service', to='setup.companylocation', verbose_name='Location')),
                ('service_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_location_price', to='setup.service', verbose_name='Service Code')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_loc_price_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Service Location Price Registration',
                'verbose_name_plural': 'Service Location Price Registrations',
                'db_table': 'service_location_price',
                'unique_together': {('company', 'locations', 'service_code')},
            },
        ),
    ]
