# Generated by Django 5.1.3 on 2024-11-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0040_servicelocationprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelocationprice',
            name='item_barcode',
            field=models.CharField(blank=True, max_length=100, verbose_name='Item Barcode'),
        ),
    ]
