# Generated by Django 5.1.3 on 2024-11-25 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0041_alter_servicelocationprice_item_barcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_tax', models.BooleanField(default=False, verbose_name='Is Tax Included')),
                ('remarks', models.TextField(blank=True, default='', max_length=100, null=True, verbose_name='Remarks')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ServiceTax_company_locations_price', to='setup.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_loc_price_created_byTax', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('locations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ServiceTax_location_service', to='setup.companylocation', verbose_name='Location')),
                ('service_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_location_Tax', to='setup.service', verbose_name='Service Code')),
                ('tax_code', models.ManyToManyField(blank=True, related_name='service_taxesLocTax', to='setup.taxcode', verbose_name='Tax Code(s)')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_loc_price_updated_byTax', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Service Location Tax Registration',
                'verbose_name_plural': 'Service Location Tax Registrations',
                'db_table': 'service_Tax',
                'unique_together': {('company', 'locations', 'service_code')},
            },
        ),
    ]
