# Generated by Django 5.1.3 on 2024-11-25 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0042_servicetax'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetax',
            options={'verbose_name': 'Service Tax Registration', 'verbose_name_plural': 'Service Tax Registrations'},
        ),
        migrations.AlterUniqueTogether(
            name='servicetax',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='servicetax',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_tax_company', to='setup.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='servicetax',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_tax_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='servicetax',
            name='remarks',
            field=models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='servicetax',
            name='service_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_tax_service', to='setup.service', verbose_name='Service Code'),
        ),
        migrations.AlterField(
            model_name='servicetax',
            name='tax_code',
            field=models.ManyToManyField(related_name='service_tax_codes', to='setup.taxcode', verbose_name='Tax Codes'),
        ),
        migrations.AlterField(
            model_name='servicetax',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_tax_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterModelTable(
            name='servicetax',
            table='service_tax',
        ),
        migrations.RemoveField(
            model_name='servicetax',
            name='locations',
        ),
        migrations.AddField(
            model_name='servicetax',
            name='locations',
            field=models.ManyToManyField(related_name='service_tax_locations', to='setup.companylocation', verbose_name='Locations'),
        ),
    ]
