# Generated by Django 5.1.3 on 2024-11-25 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0045_alter_supplierregistration_app_wtax_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierReferralFeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReferralFee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Referral Fee Amount')),
                ('ReferralFeePre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Referral Fee %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_registration_ReferralFee', to='setup.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_ReferralFee_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_ReferralFee_details_departments', to='setup.department', verbose_name='Associated Departments')),
                ('locations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_ReferralFee_locations_department', to='setup.companylocation', verbose_name='Location')),
                ('services_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_ReferralFee_service_details', to='setup.service', verbose_name='Services Code')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_detailsReferralFee', to='setup.supplierregistration', verbose_name='Supplier')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_ReferralFee_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Supplier ReferralFee Detail',
                'verbose_name_plural': 'Supplier ReferralFee Details',
                'db_table': 'supplier_ReferralFee_details',
                'constraints': [models.UniqueConstraint(fields=('company', 'locations', 'supplier', 'departments', 'services_code'), name='unique_supplier_ReferralFee_details')],
            },
        ),
    ]
